name: Generate Changelog

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  changelog:
    name: Generate CHANGELOG.md
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for changelog history

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install auto-changelog
        run: npm install -g auto-changelog

      - name: Configure Git identity
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Generate CHANGELOG.md
        run: auto-changelog --tag-prefix v --output CHANGELOG.md

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit changelog before rebase
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for ${{ github.ref_name }}" || echo "No changes to commit"

      - name: Fetch and rebase before push
        run: |
          git fetch origin main
          git rebase origin/main

      - name: Commit and push changelog
        run: |
          git checkout main
          git pull origin main
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for ${{ github.ref_name }}" || echo "No changes to commit"
          git push origin main
