name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up zip utility
        run: sudo apt-get install -y zip

      - name: Build CLI zip package
        run: |
          mkdir -p dist
          zip -r dist/jamf-ddm-sofa-cli.zip bin install.sh man README.md LICENSE

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for ${{ github.ref_name }}"
          git push origin HEAD:main


      - name: Delete existing release (if exists)
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/jamf-ddm-sofa-cli.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
